plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace = 'dev.bsb.moakeyvim'
    compileSdk = 35

    defaultConfig {
        applicationId = "dev.bsb.moakeyvim"
        minSdk = 30
        targetSdk = 35
        versionCode = 13
        versionName = "1.0.13"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    testOptions {
        unitTests {
            returnDefaultValues = true
        }
    }
    buildFeatures {
        viewBinding = true
        buildConfig = true
    }
}

dependencies {
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.androidx.autofill
    implementation libs.androidx.preference
    implementation libs.material
    implementation libs.koin.android
    implementation libs.emoji2.emojipicker
    implementation libs.kotlinx.coroutines.android
    testImplementation libs.junit
    testImplementation libs.kotlinx.coroutines.test
    testImplementation 'org.json:json:20240303'
    androidTestImplementation libs.androidx.test.ext.junit
    androidTestImplementation libs.espresso.core
}
